index:
    path: /
    controller: App\Controller\DefaultController::indexAction
    
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
    
navbar:
    path: /navbar
    controller: App\Controller\DefaultController::navbarAction
    
